"""
model.py — Deep-Learning QEM Pipeline (Stub)
=============================================

This module will house the Quantum Error Mitigation model(s):

    • **QEMAutoencoder** — a denoising autoencoder that maps noisy
      probability distributions back to their ideal counterparts.
    • **QEMMLP** — a simpler MLP baseline for comparison.

Architecture decisions to be made:
    - Input dim  = 2^n (one probability per basis state)
    - Output dim = 2^n
    - Loss function: KL-divergence or MSE on probability vectors
    - Training data: pairs of (noisy_dist, ideal_dist) generated by
      running the same Grover circuit with and without noise models.

Implementation will follow once the noise simulation pipeline is in
place (see `src/quantum/noise_models.py` — to be created).
"""

from __future__ import annotations

# Placeholder — implementation coming soon
# import torch
# import torch.nn as nn
